name: Build iOS (Libretro)
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 
      - name: Configure & Build 🔧 
        run: |
          mkdir build
          cd build
          cmake -GXcode -DCMAKE_SYSTEM_NAME=iOS ../
          cmake --build . --target SkyEmuRetro --config Release
          mkdir Payload
          cp -R libSkyEmuRetro.dylib Payload/SkyEmu.app
          zip -r SkyEmuRetro.ipa Payload
      - name: GH Release 🚀
        # You may pin to the exact commit or the version.
        uses: actions/upload-artifact@v2
        with:
           name: iOSRelease (Libretro)
           path: build/SkyEmu.ipa
        #uses: softprops/action-gh-release@v0.1.5
        #with:
        #  # Note-worthy description of changes in release
        #  # body: # optional
        #  # Path to load note-worthy description of changes in release from
        #  # body_path: # optional
        #  # Gives the release a custom name. Defaults to tag name
        #  name: LinuxRelease
        #  # Identify the release as a prerelease. Defaults to false
        #  prerelease: True
        #  # Newline-delimited list of path globs for asset files to upload
        #  files: build/bin/*
 
