name: Build FreeBSD
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: macos-12
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Configure & Build 🔧
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          envs: 'MYTOKEN MYTOKEN2'
          usesh: true
          prepare: |
            pkg install -y curl

          run: |
            mkdir build
            cd build
            cmake .. && cmake --build .
      - name: GH Release 🚀
        # You may pin to the exact commit or the version.
        uses: actions/upload-artifact@v2
        with:
           name: LinuxRelease
           path: build/bin/
       
