name: Build Android
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 
      - name: Setup Ninja 
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Configure & Build 🔧 
        run: |
          mkdir build
          cd build
          ../tools/build_android.sh
          
      - name: GH Release 🚀
        # You may pin to the exact commit or the version.
        uses: actions/upload-artifact@v2
        with:
           name: AndroidRelease
           path: build/cmake_build
        #uses: softprops/action-gh-release@v0.1.5
        #with:
        #  # Note-worthy description of changes in release
        #  # body: # optional
        #  # Path to load note-worthy description of changes in release from
        #  # body_path: # optional
        #  # Gives the release a custom name. Defaults to tag name
        #  name: LinuxRelease
        #  # Identify the release as a prerelease. Defaults to false
        #  prerelease: True
        #  # Newline-delimited list of path globs for asset files to upload
        #  files: build/bin/*
 
